### ISSUE TITLE
为什么博客没有评论系统？

### ISSUE THREAD

**Issue by juteman** [LiZeC123/lizec123.github.io#1]
有很多想吐槽的，总不能开issues 吐槽吧

**Comment by LiZeC123** [comment]
本来想搞一个的,但是看着注册太麻烦了,于是就凉了.  那我最近加一个吧. 要是等不及了,可以给我私聊哈

**Comment by LiZeC123** [comment]
评论区已加, 配置完才发现需要翻.墙. 相信这都不是问题,你自己看着办哈

**Comment by juteman** [comment]
给你弄了个友情链接

**Comment by LiZeC123** [comment]
嗯嗯,谢谢了,有机会的话也给你搞一个友情链接
