### ISSUE TITLE
如何优雅的输入矩阵公式 | LiZeC的博客

### ISSUE THREAD

**Issue by LiZeC123** [LiZeC123/lizec123.github.io#76]
https://lizec.top/2019/07/03/%E5%A6%82%E4%BD%95%E4%BC%98%E9%9B%85%E7%9A%84%E8%BE%93%E5%85%A5%E7%9F%A9%E9%98%B5%E5%85%AC%E5%BC%8F/

**Comment by CAM1113** [comment]
王灿到此一游
